### Hehehe redirect ###

$mellow=~/.config/hypr
$in_mellow=~/.config/hypr/mellow_hypr

source = $mellow/hyprvar.conf
source = $in_mellow/general.conf
source = $in_mellow/env.conf
source = $in_mellow/decorations.conf
source = $in_mellow/animations.conf
source = $in_mellow/execs.conf
source = $in_mellow/keybinds.conf
source = $in_mellow/misc.conf
source = $in_mellow/rules.conf
source = $in_mellow/plugins.conf
