#################
### Variables ###
#################

# Yaaaayyyy!

### Keys ###

$wdnw = Super
$wdnwa = Alt_Super
$wdnwc = Ctrl_Super
$wdnws = Super_Shift
$wdnwsc = Super_Ctrl_Shift

### Apps ###

$terminal = kitty
$file = nautilus
$launcher = ~/.config/rofi/scripts/main-ctrl.sh
$launcher_app = rofi -config ~/.config/rofi/apps.rasi -show drun
$ctrl_panel = swaync-client -t
$notif_test = notify-send "Ligma" "Balls"
$logout = wlogout
