# BACKGROUND
background {
    monitor =
#    path = ~/.config/hypr/hyprlock/blackholeV1.png
    color= rgba(0,0,0,0)
    blur_passes = 2
    blur_size = 8
    noise = 0.015
    contrast = 0.9
    brightness = 0.85
    vibrancy = 0.6 
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
    hide_cursor = false
}

# Time-Hour
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I")</span>"
    color = rgba(255, 255, 255, 1)
    font_size = 125
    font_family = MapleMono
    position = -80, 190
    halign = center
    valign = center
}

# Time-Minute
label {
    monitor = DP-4
    text = cmd[update:1000] echo "<span>$(date +"%M")</span>"
    color = rgb(5b31c7)
    font_size = 125
    font_family = MapleMono
    position = 0, 70
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor = DP-4
    text = cmd[update:1000] echo -e "$(date +"%d %B, %a.")"
    color = rgba(255, 255, 255, 100)
    font_size = 22
    font_family = MapleMono Italic
    position = 20, -8
    halign = center
    valign = center
}

# USER
label {
    monitor = DP-4
    text =     $USER
    color = rgba(216, 222, 233, 0.80)
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    font_size = 22
    font_family = MapleMono Bold
    position = 0, -220
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor = DP-4
    size = 300, 60
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(200, 200, 200)
    fade_on_empty = true
    font_family = MapleMono Thin
    placeholder_text = <i><span foreground="##ffffff99">Password</span></i>
    hide_input = false
    position = 0, -290
    halign = center
    valign = center
}

# Reboot
label {
    monitor =
    text = 󰜉
    color = rgba(255, 255, 255, 0.6)
    font_size = 50
    onclick = reboot now
    position = 0, 100
    halign = center
    valign = bottom
}

# Power off
label {
    monitor =
    text = 󰐥
    color = rgba(255, 255, 255, 0.6)
    font_size = 50
    onclick = shutdown now
    position = 200, 100
    halign =center 
    valign = bottom
}

# Suspend
label {
    monitor =
    text = 󰤄
    color = rgba(255, 255, 255, 0.6)
    font_size = 50
    onclick = systemctl suspend
    position = -200, 100
    halign = center
    valign = bottom
}

# CURRENT SONG
label {
    monitor = DP-4
    text = cmd[update:1000] echo "$(~/.config/hypr/hyprlock/songdetail.sh)" 
    color = rgb(5b31c7)
    font_size = 18
    font_family = MapleMono
    position = 0, 0
    halign = center
    valign = bottom
}