
# ##################################################################################
# WELCOME USER!
# This is my first fully custom-made dotfile! with everything to satisfy your need!
# ##################################################################################

### Note ###

# I will be using Caelestia's shell BUT not making something that will copy the author (s)
# I am impressed by the creator's work and.. wanted to do something similar but not a copy
# Also this part here called 'Note' will be used to put the new updates as the dotfile continues
# (PS: I'm making a spotify-ish project so if you want you could look there!)

# This is an early alpha of a project so DONT use it now!
# Version: Alpha V0

###############
### Sources ###
###############

$testing=~/.config/mellow/Github/Mellow/Hyprland_config/hyprland_mellow.conf
$sources=~/.config/hypr/direction.conf
$variable_perso=~/.config/hypr/hyprvar_pers.conf

# Unstablleeee

# source = $testing

# source = $testing
source = $variable_perso

# Stabel

source = $sources
