#############
### Execs ###
#############

# For steam wallpapers the path is: /home/matteo/.steam/steam/steamapps/workshop/content/431960/

exec-once = mpvpaper -o "no-audio loop" DP-4 ~/Pictures/wallpapers/1L04S8~U.mp4
exec-once = waybar
exec-once = python ~/.config/waybar/scripts/ddc_daemon.py
exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle
exec-once = kitty
exec-once = swaync
