#############
### Execs ###
#############

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = swww-daemon --no-cache
exec-once = swww img ~/Pictures/wallpapers/images/Pink_wallpaper_up.jpeg
exec-once = waybar
exec-once = python3 ~/.config/waybar/scripts/ddc_daemon.py
exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle
exec-once = hyprpm reload
exec-once = hyprsunset
exec-once = kitty
exec-once = swaync


