################
### Keybinds ###
################

## for variables look at hypr_var.conf

# My favorite part (and longest one)

### Mains apps / commands ###

binde = $wdnw, T, exec, $terminal
bind = $wdnws, F, exec, $file
bind = $wdnw, space, exec, $launcher
bind = $wdnw, R, exec, $launcher_app
binde = $wdnw, Q, killactive
bind = $wdnws, Q, forcekillactive
bind = $wdnwsc, Q, exit
bind = $wdnw, L, exec, $logout
bind = $wdnw, P, exec, $ctrl_panel
bind = $wdnws, P, exec, $notif_test

### Workspaces ###

# Switch workspaces

bind = $wdnw, 1, workspace, 1
bind = $wdnw, 2, workspace, 2
bind = $wdnw, 3, workspace, 3
bind = $wdnw, 4, workspace, 4
bind = $wdnw, 5, workspace, 5
bind = $wdnw, 6, workspace, 6
bind = $wdnw, 7, workspace, 7
bind = $wdnw, 8, workspace, 8
bind = $wdnw, 9, workspace, 9
bind = $wdnw, 0, workspace, 10

# Special workspaces (?)

bind = $wdnw, M, togglespecialworkspace, music
bind = $wdnw, S, togglespecialworkspace, special

# REAL switch

bind = $wdnwc, right, swapwindow, r
bind = $wdnwc, left, swapwindow, l
bind = $wdnwc, d, swapwindow, r
bind = $wdnwc, a, swapwindow, l
bind = $wdnwc, w, swapwindow, u
bind = $wdnwc, s, swapwindow, d
bind = $wdnwc, up, swapwindow, u
bind = $wdnwc, down, swapwindow, d

# Left <-> right

bind = $wdnw, left, workspace, r-1
bind = $wdnw, right, workspace, r+1

# Move a window to another workspace

bind = $wdnws, 1, movetoworkspace, 1
bind = $wdnws, 2, movetoworkspace, 2
bind = $wdnws, 3, movetoworkspace, 3
bind = $wdnws, 4, movetoworkspace, 4
bind = $wdnws, 5, movetoworkspace, 5
bind = $wdnws, 6, movetoworkspace, 6
bind = $wdnws, 7, movetoworkspace, 7
bind = $wdnws, 8, movetoworkspace, 8
bind = $wdnws, 9, movetoworkspace, 9
bind = $wdnws, 0, movetoworkspace, 10

# Left <-> right

bind = $wdnws, left, movetoworkspace, r-1
bind = $wdnws, right, movetoworkspace, r+1

# For scrolling updt

bind = $wdnwa, left, layoutmsg, move -col
bind = $wdnwa, right, layoutmsg, move +col

### Windows ###

bindm = $wdnw, mouse:272, movewindow
bindm = $wdnw, mouse:273, resizewindow
bind = $wdnw, F, fullscreen
bind = $wdnw, V, togglefloating

# Modeeeee

# bind = $wdnw+Ctrl, Tab,  

# Sounddddddd
bindel = , F12, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , F11, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = , F10, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# playerctl

bindl = , F7, exec, playerctl previous
bindl = , F9, exec, playerctl next
bindl = , F8, exec, playerctl play-pause

# screenshot?

bind = Ctrl, F1, exec, grim -g "$(slurp -d)" - | wl-copy