################
### Keybinds ###
################

# My favorite part (and longest one)

### Mains apps / commands ###

bind = Super, T, exec, kitty
bind = Super_Shift, Q, exit
bind = Super, R, exec, rofi -show combi #For now wofi is just a placeholder bc i gotta be configuring tofi first
bind = Super, Q, killactive
bind = Super, L, exec, wlogout 
bind = Super, P, exec, swaync-client -t
bind = Super_Shift, P, exec, notify-send "Ligma" "Balls"

### Workspaces ###

# Switch workspaces

bind = Super, 1, workspace, 1
bind = Super, 2, workspace, 2
bind = Super, 3, workspace, 3
bind = Super, 4, workspace, 4
bind = Super, 5, workspace, 5
bind = Super, 6, workspace, 6
bind = Super, 7, workspace, 7
bind = Super, 8, workspace, 8
bind = Super, 9, workspace, 9
bind = Super, 0, workspace, 10

# REAL switch

bind = Ctrl+Super, right, swapwindow, r
bind = Ctrl+Super, left, swapwindow, l
bind = Ctrl+Super, d, swapwindow, r
bind = Ctrl+Super, a, swapwindow, l
bind = Ctrl+Super, w, swapwindow, u
bind = Ctrl+Super, s, swapwindow, d
bind = Ctrl+Super, up, swapwindow, u
bind = Ctrl+Super, down, swapwindow, d

# Left <-> right

bind = Super, left, workspace, r-1
bind = Super, right, workspace, r+1

# Move a window to another workspace

bind = Super_Shift, 1, movetoworkspace, 1
bind = Super_Shift, 2, movetoworkspace, 2
bind = Super_Shift, 3, movetoworkspace, 3
bind = Super_Shift, 4, movetoworkspace, 4
bind = Super_Shift, 5, movetoworkspace, 5
bind = Super_Shift, 6, movetoworkspace, 6
bind = Super_Shift, 7, movetoworkspace, 7
bind = Super_Shift, 8, movetoworkspace, 8
bind = Super_Shift, 9, movetoworkspace, 9
bind = Super_Shift, 0, movetoworkspace, 10

# Left <-> right

bind = Super_Shift, left, movetoworkspace, r-1
bind = Super_Shift, right, movetoworkspace, r+1

### Windows ###

bindm = Super, mouse:272, movewindow
bindm = Super, mouse:273, resizewindow
bind = Super, F, fullscreen
bind = Super, V, togglefloating
bind = Super, V, centerwindow

# Modeeeee

# bind = Super+Ctrl, Tab,  

# Sounddddddd
bind = Ctrl, F12, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = Ctrl, F11, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = Ctrl, F10, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

bind = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

