#####################
### Miscellaneous ###
#####################

misc {
   # disable_hyprland_logo = # not sure yet... (i'll add it after i've set up wallpapers)
    disable_scale_notification = true
    session_lock_xray = 1
   font_family = MapleMono 
}

ecosystem {
   enforce_permissions = false
}

