plugin {
    hyprtrails {
        color = rgb(ffe3A9)
    }

    hyprscrolling {
        column_width = 0.7
        fullscreen_on_one_column = false
    }

    hyprbars {
        enable = false
        bar_height = 20
        bar_color = rgb(1e1e1e)
#        col.text = 
        bar_text_size = 12
        bar_text_font = MapleMono
        bar_button_padding = 12
        bar_padding = 10
        bar_precedence_over_border = true
#        hyprbars-button = $color1, 20, , hyprctl dispatch killactive
#        hyprbars-button = $color3, 20, , hyprctl dispatch fullscreen 2
#        hyprbars-button = $color4, 20, , hyprctl dispatch togglefloating
    }
}
