### From Caelestia (thxxxxx!) ###

# Picture in picture (resize and move done via script)

windowrule = move 100%-w-2% 100%-w-3%, match:title Picture(-| )in(-| )[Pp]icture  # Initial move so window doesn't shoot across the screen from the center
windowrule = keep_aspect_ratio true, match:title Picture(-| )in(-| )[Pp]icture
windowrule = float true, match:title Picture(-| )in(-| )[Pp]icture
windowrule = pin true, match:title Picture(-| )in(-| )[Pp]icture

# Special workspaces

windowrule = workspace special:sysmon, match:class btop
windowrule = workspace special:music, match:class feishin|Spotify|Supersonic|Cider|com.github.th_ch.youtube_music|Plexamp
windowrule = workspace special:music, match:initial_title Spotify( Free)?  # Spotify wayland, it has no class for some reason
windowrule = workspace special:communication, match:class discord|equibop|vesktop|whatsapp|ZapZap
windowrule = workspace special:todo, match:class Todoist

### for desabling blur ig?

layerrule = blur off, match:namespace waybar
layerrule = blur on, match:namespace logout_dialog
