# From Caelestia (thxxxxx!)

# Picture in picture (resize and move done via script)

windowrule = move 100%-w-2% 100%-w-3%, match:title Picture(-| )in(-| )[Pp]icture  # Initial move so window doesn't shoot across the screen from the center
windowrule = keep_aspect_ratio true, match:title Picture(-| )in(-| )[Pp]icture
windowrule = float true, match:title Picture(-| )in(-| )[Pp]icture
windowrule = pin true, match:title Picture(-| )in(-| )[Pp]icture