# Mellow Space theme 

foreground #eaddcf
background #1a1325
cursor #ffe3a9

# Normal colors
color0 #1a1325
color1 #39149c
color2 #ffe3a9
color3 #b093ff
color4 #5f4d8c
color5 #a67ee9
color6 #ffe3a9
color7 #eaddcf

# Bright colors
color8 #2d2540
color9 #5b31c7
color10 #fff0ca
color11 #c3afff
color12 #8c7acd
color13 #a287ff
color14 #fff2c7
color15 #ffffff
