# 888 88P ,e,   d8     d8             
# 888 8P   "   d88    d88   Y8b Y888P 
# 888 K   888 d88888 d88888  Y8b Y8P  
# 888 8b  888  888    888     Y8b Y   
# 888 88b 888  888    888      888    
#                              888    
#                              888    
#     e   e             888 888                         
#    d8b d8b     ,e e,  888 888  e88 88e  Y8b Y8b Y888P 
#   e Y8b Y8b   d88 88b 888 888 d888 888b  Y8b Y8b Y8P  
#  d8b Y8b Y8b  888   , 888 888 Y888 888P   Y8b Y8b "   
# d888b Y8b Y8b  "YeeP" 888 888  "88 88"     YP  Y8P    


### FONT ###

font_family      Maplemono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 10.0

disable_ligatures never

font_features none

### CURSOR ###

cursor #ffe3A9
cursor_text_color #ffe3A9
cursor_shape beam
cursor_stop_blinking_after 0.0
cursor_trail 1
cursor_trail_color #ffe3A9

### SCROLL ###

scrollbar scrolled-and-hovered
scrollbar_width 1
scrollbar_handle_opacity 0.75
scrollbar_radius 0.5
scrollbar_hitbox_expansion 0.4
scrollbar_track_opacity 0.1
scrollbar_track_hover_opacity 0.1
scrollback_pager_history_size 75
wheel_scroll_multiplier 4.0

### MOUSE ###

mouse_hide_wait 1.0
url_color #8CCDEB
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh fish zsh bash
show_hyperlink_targets yes
underline_hyperlinks always
strip_trailing_spaces smart
select_by_word_characters @-./_~?&=%+#
mouse_map left click ungrabbed

### PERFORMANCE ###

# i have nthing bc default is gud

### TERMINAL BELL (?) ###
 
 # Wtf??? idk what it is :(
 
### WINDOW LAYOUT ###

remember_window_size  yes
initial_window_width  640
initial_window_height 400
confirm_os_window_close -1

### TAB BAR ###

tab_bar_edge top
tab_bar_style powerline
tab_bar_min_tabs 2
tab_bar_background #ffe3A9
tab_bar_margin_color #725cad

### COLOR SCHEME AND ELSE ###

foreground #dddddd
background #000000

background_opacity 0.7
background_blur 1
dynamic_background_opacity yes

### ADVANCED ANS ELSE ###

shell fish
editor nano
close_on_child_death yes
allow_remote_control yes
notify_on_cmd_finish unfocused

### OS SPECIFIC TWEAKS ###

# I'm too dumb for this :(

### SHORTCUUUUUUTTTTSSSS ###

map ctrl+v paste_from_clipboard
map page_up scroll_page_up
map page_down scroll_page_down

### Colors? ###

include ~/.config/mellow/Github/Mellow/Themes/kitty/kitty-theme.conf
