# Mellow Space theme 

foreground #eaddcf
background #1a1325
cursor #ffe3a9

# Normal colors

#Black
color0 #1a1325

# mellow black 
color8 #2d2540

#Hwite
color7 #ffffff

#Hwite mellow
color15 #eaddcf

#Reddd
color1 #9e2a3a

#Blu
color4 #1a3d64

#mellow blu
color12 #39149c

#Greeeem
color2 #366639

#mellow greeen
color10 #fff0ca

#Purpol
color5 #a67ee9

#mellow porpol
color13 #c3afff

#Yello (blue?)
color3 #ffe3a9

#mellow yelloww (the same)
color11 #ffe3a9

#Orange 
color9 #965035

#mellow C.C.1 (other Complementary Colors (for mor choices))
color6 #fff2c7

#mellow C.C.2
color14 #b093ff



## Pther nooon-mentioned colors ig?

#dark purpol
 #8c7acd

#dark purpol
 #5f4d8c

#bright purple
 #a287ff
